// Generated by `wit-bindgen` 0.52.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod ochagavia {
  pub mod test {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Rng{
        handle: _rt::Resource<Rng>,
      }

      impl Rng{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Rng{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "ochagavia:test/host-types@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]rng"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Rng {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn next_u32(&self,upper_bound_inclusive: u32,) -> u32{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "ochagavia:test/host-types@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]rng.next-u32"]
              fn wit_import0(_: i32, _: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, _: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32, _rt::as_i32(&upper_bound_inclusive));
            ret as u32
          }
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod ochagavia {
    pub mod test {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod guest_types {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type Rng = super::super::super::super::ochagavia::test::host_types::Rng;

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Greeter{
          handle: _rt::Resource<Greeter>,
        }

        type _GreeterRep<T> = Option<T>;

        impl Greeter{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Greeter`.
          pub fn new<T: GuestGreeter>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _GreeterRep<T> = Some(val);
            let ptr: *mut _GreeterRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestGreeter>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestGreeter>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestGreeter>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestGreeter` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _GreeterRep<T>) };
          }

          fn as_ptr<T: GuestGreeter>(&self) -> *mut _GreeterRep<T> {
            Greeter::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Greeter`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct GreeterBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Greeter>,
        }

        impl<'a> GreeterBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestGreeter>(&self) -> &'a T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _GreeterRep<T> {
            Greeter::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Greeter{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]ochagavia:test/guest-types@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]greeter"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_constructor_greeter_cabi<T: GuestGreeter>(arg0: i32,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          Greeter::new(T::new(super::super::super::super::ochagavia::test::host_types::Rng::from_handle(arg0 as u32)))
        };
        (result0).take_handle() as i32
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_method_greeter_greet_cabi<T: GuestGreeter>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T::greet(GreeterBorrow::lift(arg0 as u32 as usize).get())
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      let vec2 = (result0.into_bytes()).into_boxed_slice();
      let ptr2 = vec2.as_ptr().cast::<u8>();
      let len2 = vec2.len();
      ::core::mem::forget(vec2);
      *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
      *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
      ptr1
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_method_greeter_greet<T: GuestGreeter>(arg0: *mut u8,) { unsafe {
      let l0 = *arg0.add(0).cast::<*mut u8>();
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l0, l1, 1);
    } }
    pub trait Guest {
      type Greeter: GuestGreeter;
    }
    pub trait GuestGreeter: 'static {

      #[doc(hidden)]
      unsafe fn _resource_new(val: *mut u8) -> u32
      where Self: Sized
      {
        
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "[export]ochagavia:test/guest-types@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[resource-new]greeter"]
          fn new(_: *mut u8, ) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
        
        unsafe { new(val) as u32 }
      }

      #[doc(hidden)]
      fn _resource_rep(handle: u32) -> *mut u8
      where Self: Sized
      {
        
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "[export]ochagavia:test/guest-types@0.1.0")]
        unsafe extern "C" {
          #[link_name = "[resource-rep]greeter"]
          fn rep(_: i32, ) -> *mut u8;
        }

        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
        
        unsafe { rep(handle as i32) }
      }

      
      #[allow(async_fn_in_trait)]
      fn new(r: Rng,) -> Self;
      #[allow(async_fn_in_trait)]
      fn greet(&self,) -> _rt::String;
    }
    #[doc(hidden)]

    macro_rules! __export_ochagavia_test_guest_types_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "ochagavia:test/guest-types@0.1.0#[constructor]greeter")]
        unsafe extern "C" fn export_constructor_greeter(arg0: i32,) -> i32 {
          unsafe { $($path_to_types)*::_export_constructor_greeter_cabi::<<$ty as $($path_to_types)*::Guest>::Greeter>(arg0) }
        }
        #[unsafe(export_name = "ochagavia:test/guest-types@0.1.0#[method]greeter.greet")]
        unsafe extern "C" fn export_method_greeter_greet(arg0: *mut u8,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_method_greeter_greet_cabi::<<$ty as $($path_to_types)*::Guest>::Greeter>(arg0) }
        }
        #[unsafe(export_name = "cabi_post_ochagavia:test/guest-types@0.1.0#[method]greeter.greet")]
        unsafe extern "C" fn _post_return_method_greeter_greet(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_method_greeter_greet::<<$ty as $($path_to_types)*::Guest>::Greeter>(arg0) }
        }

        const _: () = {
          #[doc(hidden)]
          #[unsafe(export_name = "ochagavia:test/guest-types@0.1.0#[dtor]greeter")]
          #[allow(non_snake_case)]
          unsafe extern "C" fn dtor(rep: *mut u8) {
            unsafe {
              $($path_to_types)*::Greeter::dtor::<
              <$ty as $($path_to_types)*::Guest>::Greeter
              >(rep)
            }
          }
        };
        
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_ochagavia_test_guest_types_0_1_0_cabi;

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct _RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
    static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);

  }

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::string::String;
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_my_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::ochagavia::test::guest_types::__export_ochagavia_test_guest_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::ochagavia::test::guest_types);
  )
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.52.0:ochagavia:test@0.1.0:my-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 429] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xae\x02\x01A\x02\x01\
A\x05\x01B\x04\x04\0\x03rng\x03\x01\x01h\0\x01@\x02\x04self\x01\x15upper-bound-i\
nclusivey\0y\x04\0\x14[method]rng.next-u32\x01\x02\x03\0\x1fochagavia:test/host-\
types@0.1.0\x05\0\x02\x03\0\0\x03rng\x01B\x0a\x02\x03\x02\x01\x01\x04\0\x03rng\x03\
\0\0\x04\0\x07greeter\x03\x01\x01i\x01\x01i\x02\x01@\x01\x01r\x03\0\x04\x04\0\x14\
[constructor]greeter\x01\x05\x01h\x02\x01@\x01\x04self\x06\0s\x04\0\x15[method]g\
reeter.greet\x01\x07\x04\0\x20ochagavia:test/guest-types@0.1.0\x05\x02\x04\0\x1d\
ochagavia:test/my-world@0.1.0\x04\0\x0b\x0e\x01\0\x08my-world\x03\0\0\0G\x09prod\
ucers\x01\x0cprocessed-by\x02\x0dwit-component\x070.244.0\x10wit-bindgen-rust\x06\
0.52.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

